 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Akregator", "akregator  -caption Akregator", "/usr/share/icons/hicolor/16x16/apps/akregator.png" },
     {"Avahi SSH服务器浏览器", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC服务器浏览器", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Blogilo", "blogilo  -caption Blogilo", "/usr/share/icons/hicolor/16x16/apps/blogilo.png" },
     {"BlueDevil", "bluedevil-monolithic"},
     {"Chromium", "chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Dropbox", "dropboxd", "/usr/share/pixmaps/dropbox.png" },
     {"EConnMan", "econnman-bin"},
     {"EConnMan with Agent", "econnman-bin --agent"},
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"KGet", "kget -caption KGet  ", "/usr/share/icons/hicolor/16x16/apps/kget.png" },
     {"KMail", "kmail -caption KMail ", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KMail Header Theme Editor", "headerthemeeditor", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KNode", "knode -caption KNode", "/usr/share/icons/hicolor/16x16/apps/knode.png" },
     {"KPPP", "kppp", "/usr/share/icons/hicolor/16x16/apps/kppp.png" },
     {"KRDC", "krdc -caption KRDC "},
     {"KTnef", "ktnef ", "/usr/share/icons/hicolor/48x48/apps/ktnef.png" },
     {"Konqueror", "kfmclient openProfile webbrowsing", "/usr/share/icons/hicolor/16x16/apps/konqueror.png" },
     {"Kopete", "kopete -caption Kopete ", "/usr/share/icons/hicolor/16x16/apps/kopete.png" },
     {"Krfb", "krfb -caption Krfb ", "/usr/share/icons/gnome/16x16/apps/krfb.png" },
     {"Pidgin 互联网通讯程序", "pidgin", "/usr/share/icons/hicolor/16x16/apps/pidgin.png" },
     {"Psi", "psi ", "/usr/share/icons/hicolor/16x16/apps/psi.png" },
     {"Qtransmission Bittorrent Client", "transmission-qt ", "/usr/share/pixmaps/transmission-qt.png" },
     {"Skype", "skype ", "/usr/share/icons/hicolor/16x16/apps/skype.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Thunderbird", "thunderbird ", "/usr/share/icons/hicolor/16x16/apps/thunderbird.png" },
     {"Vidalia", "vidalia", "/usr/share/icons/hicolor/16x16/apps/vidalia.png" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"aLinkCreator", "alc", "/usr/share/pixmaps/alc.xpm" },
     {"aMule", "amule", "/usr/share/pixmaps/amule.xpm" },
     {"aMuleGUI", "amulegui", "/usr/share/pixmaps/amulegui.xpm" },
     {"wxCas", "wxcas", "/usr/share/pixmaps/wxcas.xpm" },
     {"信使(iptux)", "iptux", "/usr/share/icons/hicolor/16x16/apps/ip-tux.png" },
     {"坚果云 ", "sh -c \"nohup /opt/nutstore/bin/nutstore-pydaemon.py >/dev/null 2>&1 &\"", "/usr/share/icons/hicolor/64x64/apps/nutstore.png" },
     {"阿里旺旺", "AliWangWang", "/usr/share/pixmaps/AliWangWang.png" },
 }

 local menudb53804b7d726967c58fcc8c9ca03d27 = {
     {"AbiWord", "abiword", "/usr/share/icons/abiword_48.png" },
     {"FBReader", "FBReader ", "/usr/share/pixmaps/FBReader.png" },
     {"KAddressBook", "kaddressbook ", "/usr/share/icons/hicolor/16x16/apps/kaddressbook.png" },
     {"KMail", "kmail -caption KMail ", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KMail Header Theme Editor", "headerthemeeditor", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KOrganizer", "korganizer ", "/usr/share/icons/hicolor/16x16/apps/korganizer.png" },
     {"KTimeTracker", "ktimetracker", "/usr/share/icons/hicolor/16x16/apps/ktimetracker.png" },
     {"KTnef", "ktnef ", "/usr/share/icons/hicolor/48x48/apps/ktnef.png" },
     {"KchmViewer", "kchmviewer ", "/usr/share/pixmaps/kchmviewer.png" },
     {"Kontact", "kontact", "/usr/share/icons/hicolor/16x16/apps/kontact.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Lokalize", "lokalize  -caption Lokalize", "/usr/share/icons/hicolor/32x32/apps/lokalize.png" },
     {"Okular", "okular   -caption Okular", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"星际译王", "stardict", "/usr/share/pixmaps/stardict.png" },
 }

 local menue1b7cee794666669f55acead93513971 = {
     {"GNU 图像处理程序", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Gwenview", "gwenview  -caption Gwenview ", "/usr/share/icons/hicolor/16x16/apps/gwenview.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/inkscape.png" },
     {"KColorChooser", "kcolorchooser", "/usr/share/icons/hicolor/16x16/apps/kcolorchooser.png" },
     {"KRuler", "kruler", "/usr/share/icons/hicolor/16x16/apps/kruler.png" },
     {"KSnapshot", "ksnapshot -caption KSnapshot", "/usr/share/icons/hicolor/16x16/apps/ksnapshot.png" },
     {"KolourPaint", "kolourpaint ", "/usr/share/icons/hicolor/16x16/apps/kolourpaint.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Okular", "okular   -caption Okular", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
 }

 local menu526fe18cc54d217db3fdb0bf6c5e9bc8 = {
     {"Audacious", "audacious ", "/usr/share/icons/hicolor/48x48/apps/audacious.png" },
     {"Audacity", "audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"Dragon Player", "dragon ", "/usr/share/icons/hicolor/16x16/apps/dragonplayer.png" },
     {"JuK", "juk -caption JuK ", "/usr/share/icons/hicolor/16x16/apps/juk.png" },
     {"Kdenlive", "kdenlive  -caption \"Kdenlive\" ", "/usr/share/icons/hicolor/32x32/apps/kdenlive.png" },
     {"KsCD", "kscd -caption KsCD ", "/usr/share/icons/hicolor/16x16/apps/kscd.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"SMPlayer", "smplayer ", "/usr/share/icons/hicolor/16x16/apps/smplayer.png" },
     {"SMPlayer - YouTube 浏览器", "smtube", "/usr/share/icons/hicolor/16x16/apps/smtube.png" },
 }

 local menu8640cb1581c2ae2de5a1462405b2943b = {
     {"R", "xterm -e R", "///usr/share/pixmaps/r.png" },
 }

 local menuba08216f13dd1742157412386eee1225 = {
     {"0 A.D.", "0ad", "/usr/share/pixmaps/0ad.png" },
     {"Armagetron Advanced", "armagetronad", "/usr/share/pixmaps/armagetronad.png" },
     {"Battle for Wesnoth", "wesnoth", "/usr/share/pixmaps/wesnoth-icon.png" },
     {"Battle for Wesnoth Map Editor", "wesnoth -e", "/usr/share/pixmaps/wesnoth_editor-icon.png" },
     {"Dosbox", "dosbox", "/usr/share/pixmaps/dosbox.png" },
     {"Hedgewars", "hedgewars ", "/usr/share/pixmaps/hedgewars.png" },
     {"PlayOnLinux", "playonlinux", "/usr/share/pixmaps/playonlinux32.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Warzone 2100", "warzone2100", "/usr/share/icons/warzone2100.png" },
     {"阿莫(AMOR)", "amor", "/usr/share/icons/hicolor/16x16/apps/amor.png" },
 }

 local menude71492af019157e5a5ef958b570e760 = {
     {"AQEMU", "aqemu", "/usr/share/pixmaps/aqemu_48x48.png" },
     {"Avahi Zero浏览器", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Dolphin", "dolphin  -caption Dolphin ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"Fcitx", "fcitx", "/usr/share/icons/hicolor/16x16/apps/fcitx.png" },
     {"GParted", "/usr/bin/gparted_polkit ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"GSmartControl", "/usr/bin/gsmartcontrol", "/usr/share/icons/hicolor/16x16/apps/gsmartcontrol.png" },
     {"KDE 系统卫士", "ksysguard ", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"KDiskFree", "kdf -caption KDiskFree", "/usr/share/icons/hicolor/16x16/apps/kdf.png" },
     {"KSystemLog", "xdg_menu_su ksystemlog  -caption KSystemLog"},
     {"KUser", "xdg_menu_su kuser  -caption KUser", "/usr/share/icons/hicolor/16x16/apps/kuser.png" },
     {"KWalletManager", "kwalletmanager ", "/usr/share/icons/hicolor/16x16/apps/kwalletmanager.png" },
     {"Konsole", "konsole", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Krfb", "krfb -caption Krfb ", "/usr/share/icons/gnome/16x16/apps/krfb.png" },
     {"KwikDisk", "kwikdisk -caption KwikDisk", "/usr/share/icons/hicolor/16x16/apps/kwikdisk.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"Nepomuk 备份", "nepomukbackup"},
     {"Nepomuk 清理工具", "nepomukcleaner"},
     {"NmapSI4 - Full mode", "xdg_menu_su kdesu nmapsi4", "/usr/share/icons/hicolor/32x32/apps/nmapsi4.png" },
     {"NmapSI4 - User mode", "nmapsi4", "/usr/share/icons/hicolor/32x32/apps/nmapsi4.png" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"Q4Wine", "q4wine -b ", "/usr/share/icons/hicolor/16x16/apps/q4wine.png" },
     {"Terminator", "terminator", "/usr/share/icons/hicolor/16x16/apps/terminator.png" },
     {"TrueCrypt", "truecrypt", "/usr/share/pixmaps/truecrypt.xpm" },
     {"UNetbootin", "/usr/bin/unetbootin", "/usr/share/icons/hicolor/16x16/apps/unetbootin.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"dconf 系统配置编辑器", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/dconf-editor.png" },
     {"打印机管理", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
 }

 local menu41282bf95e43c64d579757573a03cdde = {
     {"Akonadi 控制台", "akonadiconsole", "/usr/share/icons/hicolor/16x16/apps/akonadiconsole.png" },
     {"CMake", "cmake-gui ", "/usr/share/pixmaps/CMakeSetup32.png" },
     {"Cervisia", "cervisia -caption Cervisia  ", "/usr/share/icons/hicolor/16x16/apps/cervisia.png" },
     {"Elementary Test", "elementary_test", "/usr/share/icons/elementary.png" },
     {"KAppTemplate", "kapptemplate", "/usr/share/icons/hicolor/16x16/apps/kapptemplate.png" },
     {"KCachegrind", "kcachegrind -caption KCachegrind ", "/usr/share/icons/hicolor/32x32/apps/kcachegrind.png" },
     {"KImageMapEditor", "kimagemapeditor -caption KImageMapEditor ", "/usr/share/icons/hicolor/16x16/apps/kimagemapeditor.png" },
     {"KLinkStatus", "klinkstatus   -caption KLinkStatus", "/usr/share/icons/hicolor/16x16/apps/klinkstatus.png" },
     {"KUIViewer", "kuiviewer -caption KUIViewer", "/usr/share/icons/hicolor/16x16/apps/kuiviewer.png" },
     {"Kompare", "kompare -caption Kompare -o ", "/usr/share/icons/hicolor/16x16/apps/kompare.png" },
     {"Lokalize", "lokalize  -caption Lokalize", "/usr/share/icons/hicolor/32x32/apps/lokalize.png" },
     {"OpenJDK Policy Tool", "/usr/bin/policytool", "/usr/share/icons/hicolor/16x16/apps/java.png" },
     {"Qt Assistant", "/usr/lib/qt/bin/assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Creator", "/usr/bin/qtcreator", "///usr/share/icons/hicolor/512x512/apps/QtProject-qtcreator.png" },
     {"Qt Designer", "/usr/lib/qt/bin/designer", "/usr/share/icons/hicolor/128x128/apps/designer.png" },
     {"Qt Linguist", "/usr/lib/qt/bin/linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "/usr/lib/qt/bin/qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"Umbrello", "umbrello -caption Umbrello", "/usr/share/icons/hicolor/16x16/apps/umbrello.png" },
 }

 local menu3b6fab8ae1a5e1bef9fa2320d64c4c2a = {
     {"Jovie", "jovie"},
     {"K 语音精灵", "kmouth -caption KMouth ", "/usr/share/icons/hicolor/16x16/apps/kmouth.png" },
     {"K 鼠标工具", "kmousetool -caption KMouseTool ", "/usr/share/icons/hicolor/16x16/apps/kmousetool.png" },
     {"KMag", "kmag -caption KMag ", "/usr/share/icons/hicolor/16x16/apps/kmag.png" },
 }

 local menuc9a6ee90f5d43732e3f6cf4dcaa8493c = {
     {"7-Zip FM", "7zFM", "/usr/share/icons/hicolor/32x32/apps/p7zip.png" },
     {"Akonadi 托盘", "akonaditray", "/usr/share/icons/hicolor/22x22/apps/akonaditray.png" },
     {"Ark", "ark -caption Ark ", "/usr/share/icons/hicolor/16x16/apps/ark.png" },
     {"Elementary Test", "elementary_test", "/usr/share/icons/elementary.png" },
     {"Filelight", "filelight ", "/usr/share/icons/hicolor/16x16/apps/filelight.png" },
     {"Jovie", "jovie"},
     {"K 语音精灵", "kmouth -caption KMouth ", "/usr/share/icons/hicolor/16x16/apps/kmouth.png" },
     {"K 鼠标工具", "kmousetool -caption KMouseTool ", "/usr/share/icons/hicolor/16x16/apps/kmousetool.png" },
     {"KAlarm", "kalarm -caption KAlarm ", "/usr/share/icons/hicolor/16x16/apps/kalarm.png" },
     {"KCalc", "kcalc -caption KCalc", "/usr/share/icons/gnome/16x16/apps/accessories-calculator.png" },
     {"KCharSelect", "kcharselect -caption KCharSelect", "/usr/share/icons/gnome/16x16/apps/accessories-character-map.png" },
     {"KFileReplace", "kfilereplace  -caption KFileReplace", "/usr/share/icons/hicolor/22x22/apps/kfilereplace.png" },
     {"KFloppy", "kfloppy -caption KFloppy", "/usr/share/icons/hicolor/16x16/apps/kfloppy.png" },
     {"KGpg", "kgpg ", "/usr/share/icons/hicolor/16x16/apps/kgpg.png" },
     {"KJots", "kjots -caption KJots", "/usr/share/icons/hicolor/16x16/apps/kjots.png" },
     {"KMag", "kmag -caption KMag ", "/usr/share/icons/hicolor/16x16/apps/kmag.png" },
     {"KMail Import Wizard", "importwizard", "/usr/share/icons/hicolor/64x64/apps/kontact-import-wizard.png" },
     {"KNotes", "knotes", "/usr/share/icons/hicolor/16x16/apps/knotes.png" },
     {"KTeaTime", "kteatime", "/usr/share/icons/hicolor/16x16/apps/kteatime.png" },
     {"KTimeTracker", "ktimetracker", "/usr/share/icons/hicolor/16x16/apps/ktimetracker.png" },
     {"KTimer", "ktimer", "/usr/share/icons/hicolor/16x16/apps/ktimer.png" },
     {"KWrite", "kwrite ", "/usr/share/icons/gnome/16x16/apps/accessories-text-editor.png" },
     {"Kate", "kate -b ", "/usr/share/icons/hicolor/16x16/apps/kate.png" },
     {"Kleopatra", "kleopatra", "/usr/share/icons/hicolor/16x16/apps/kleopatra.png" },
     {"Okteta", "okteta -caption Okteta ", "/usr/share/icons/hicolor/16x16/apps/okteta.png" },
     {"QStarDict", "qstardict", "/usr/share/pixmaps/qstardict.png" },
     {"Vi IMproved", "gvim -f ", "/usr/share/pixmaps/gvim.png" },
     {"synaptiks", "synaptiks"},
     {"星际译王", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"清理器", "sweeper"},
     {"键盘布局查看器", "kbd-layout-viewer", "/usr/share/icons/gnome/16x16/devices/input-keyboard.png" },
 }

xdgmenu = {
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"办公", menudb53804b7d726967c58fcc8c9ca03d27},
    {"图像", menue1b7cee794666669f55acead93513971},
    {"影音", menu526fe18cc54d217db3fdb0bf6c5e9bc8},
    {"教育", menu8640cb1581c2ae2de5a1462405b2943b},
    {"游戏", menuba08216f13dd1742157412386eee1225},
    {"系统工具", menude71492af019157e5a5ef958b570e760},
    {"编程", menu41282bf95e43c64d579757573a03cdde},
    {"辅助功能", menu3b6fab8ae1a5e1bef9fa2320d64c4c2a},
    {"附件", menuc9a6ee90f5d43732e3f6cf4dcaa8493c},
}

